### ISSUE TITLE
Uncaught Error: Class 'PhalApi\Auth\Lite' not found in...

### ISSUE THREAD

**Issue by jardn** [twodayw/auth#2]
你好，我用的是2.5的框架，用composer安装后，
注册
$di->authLite = new \PhalApi\Auth\Lite();

使用
$auth = \PhalApi\DI()->authLite;

出现了这样的错误，不知道是怎么回事，感谢！！！
Uncaught Error: Class 'PhalApi\Auth\Lite' not found in...

**Comment by kyle0007** [comment]
找到原因了。。。Phalapi后面那个api不可以大写。。。应该是移植过来没注意
$di->authLite = new \Phalapi\Auth\Lite();

**Comment by twodayw** [comment]
是的，当时没注意命名空间设置为Phalapi\Auth了
